### ISSUE TITLE
Road to v1.0.0

### ISSUE THREAD

**Issue by tiero** [vulpemventures/nigiri#113]
Nigiri has been extensively used from a while, primary by Vulpem team but also dozen of users around the world. We can say the feature set is stable enough now to target a major v1 release.

## Roadmap

- [ ] **breaking change** use more canonical ports in the docker-compose for bitcoin, elements regtest to not clash with 
- [ ] move images to Github Container Registry instead of docker
- [ ] Refactor CLI folder structure
- [ ] Fix #110 
- [ ] Implement #109
